apiVersion: v1
kind: Service
metadata:
  name: local-llm
spec:
  selector:
    app: local-llm
  ports:
  - name: llm-api
    port: 11434
    targetPort: 11434
    protocol: TCP
    nodePort: 31435
  type: NodePort
