# cici-ears/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: ai-ml
nameSuffix: -prod
commonLabels:
  variant: prod

images:
- name: ghcr.io/x81k25/cici/ears
  newTag: main

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cici-ears
    spec:
      template:
        spec:
          containers:
          - name: cici-ears
            env:
            - name: SAMPLE_RATE
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_SAMPLE_RATE
            - name: EARS_SILENCE_DURATION_MS
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_EARS_SILENCE_MS
            - name: EARS_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_EARS_DEBUG
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_LOG_LEVEL
- target:
    version: v1
    kind: Service
    name: cici-ears
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30202
