# cici-ears/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: ai-ml
nameSuffix: -prod
commonLabels:
  variant: prod

images:
- name: ghcr.io/x81k25/cici-ears
  newTag: main

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cici-ears
    spec:
      template:
        spec:
          containers:
          - name: cici-ears
            env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: EARS_DEBUG
              value: "false"
- target:
    version: v1
    kind: Service
    name: cici-ears
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30202
