# cici-mouth/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: ai-ml
nameSuffix: -prod
commonLabels:
  variant: prod

images:
- name: ghcr.io/x81k25/cici/mouth
  newTag: main

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cici-mouth
    spec:
      template:
        spec:
          containers:
          - name: cici-mouth
            env:
            - name: PIPER_VOICE
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_MOUTH_PIPER_VOICE
            - name: PIPER_SAMPLE_RATE
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_MOUTH_PIPER_SAMPLE_RATE
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_LOG_LEVEL
- target:
    version: v1
    kind: Service
    name: cici-mouth
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30203
