# cici-face/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: ai-ml
nameSuffix: -dev
commonLabels:
  variant: dev

images:
- name: ghcr.io/x81k25/cici-face
  newTag: dev

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cici-face
    spec:
      template:
        spec:
          containers:
          - name: cici-face
            env:
            - name: MIND_HOST
              value: "cici-mind-dev"
            - name: EARS_HOST
              value: "cici-ears-dev"
            - name: LOG_LEVEL
              value: "DEBUG"
- target:
    version: v1
    kind: Service
    name: cici-face
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30210
