# cici-face/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: ai-ml
nameSuffix: -prod
commonLabels:
  variant: prod

images:
- name: ghcr.io/x81k25/cici/face
  newTag: main

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cici-face
    spec:
      template:
        spec:
          containers:
          - name: cici-face
            env:
            - name: MIND_HOST
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_MIND_HOST_INTERNAL
            - name: MIND_PORT
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_MIND_PORT_INTERNAL
            - name: EARS_HOST
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_EARS_HOST_INTERNAL
            - name: EARS_PORT
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_EARS_PORT_INTERNAL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: cici-config-prod
                  key: CICI_LOG_LEVEL
- target:
    version: v1
    kind: Service
    name: cici-face
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30200
