apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -music
commonLabels:
  variant: music
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: atd
    spec:
      template:
        spec:
          containers:
          - name: gluetun
            image: 192.168.50.2:5050/media/atd/vpn:main
          - name: transmission
            image: 192.168.50.2:5050/media/atd/atd:main
            volumeMounts:
            - name: complete-volume
              mountPath: /media-cache/prod/complete
            - name: incomplete-volume
              mountPath: /media-cache/prod/incomplete
          volumes:
          - name: complete-volume
            hostPath:
              path: /k/media/music/
          - name: incomplete-volume
            hostPath:
              path: /d/media-cache/prod/incomplete
- target:
    version: v1
    kind: Service
    name: atd
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 9094
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30093