# cici-mind/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cici-mind
  labels:
    app: cici-mind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cici-mind
  template:
    metadata:
      labels:
        app: cici-mind
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8765"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: cici-mind
        image: ghcr.io/x81k25/cici/mind:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8765
        env:
        - name: MIND_HOST
          value: "0.0.0.0"
        - name: MIND_PORT
          value: "8765"
        - name: OLLAMA_HOST
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_OLLAMA_HOST
        - name: OLLAMA_PORT
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_OLLAMA_PORT
        - name: OLLAMA_MODEL
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_OLLAMA_MODEL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_LOG_LEVEL
      imagePullSecrets:
      - name: ghcr-pull-image-secret
