# cici-face/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cici-face
  labels:
    app: cici-face
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cici-face
  template:
    metadata:
      labels:
        app: cici-face
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8501"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: cici-face
        image: ghcr.io/x81k25/cici/face:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: MIND_HOST
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_MIND_HOST_INTERNAL
        - name: MIND_PORT
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_MIND_PORT_INTERNAL
        - name: EARS_HOST
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_EARS_HOST_INTERNAL
        - name: EARS_PORT
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_EARS_PORT_INTERNAL
        - name: MOUTH_HOST
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_MOUTH_HOST_INTERNAL
        - name: MOUTH_PORT
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_MOUTH_PORT_INTERNAL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cici-config-dev
              key: CICI_LOG_LEVEL
      imagePullSecrets:
      - name: ghcr-pull-image-secret
